# =========================
# DATABASE CONFIGURATION
# =========================

db.driver=com.mysql.cj.jdbc.Driver

db.url=jdbc:mysql://localhost:3306/smart_bank

db.username=root

db.password=YOUR_DB_PASSWORD


# =========================
# EMAIL CONFIGURATION
# =========================

mail.host=smtp.gmail.com

mail.port=587

mail.username=YOUR_EMAIL

mail.password=YOUR_APP_PASSWORD
